### ISSUE TITLE
Tool to characterize prediction results

### ISSUE THREAD

**Issue by torbjorgen** [Clinical-Genomics/rdds#111]
|dataset|model version|
|---|---|
|dataset: clinvar, giab, mutacc | model version: v1.7.0|

# TODOs
- [ ] ~~isualisation to set apart TP vs FP and TN vs FNs~~
- [x] F1 and thresholding for best performance point

### Test set
with threshold .05
- 171 FNs
- 32 FPs
  - 9/32 is considered possibly or probably damaging by VEP
  - 9/32 are frameshift variants (out of set compared to damaging above)
  - 6/32 are stop_gained variants
  - 4/32 are splice variants
  - 2 novel inframe insertion compared to Swegen frq

Reanalysing with threshold 0.2224 (best MCC score gives):
 - 48 FPs, 50 % increase in FPs
 - 97 FNs, 55% reduction in FNs

# Ideas going forward
- [ ] Use the model preprocessing text steps to create embeddings for text data and later on visualizations
- [ ] explainable model for further analysis
- [ ] NLP EDA tooling for dataset visualization

**Comment by torbjorgen** [comment]
[plots-v1.7.0.tar.gz](https://github.com/user-attachments/files/17817088/plots-v1.7.0.tar.gz)
