### ISSUE TITLE
SCOUT db adaptor

### ISSUE THREAD

**Issue by torbjorgen** [Clinical-Genomics/rdds#161]
https://github.com/Clinical-Genomics/servers/blob/e18b8c31b62f7b31d040582c3e2f3644014209ca/config/CGVS/config/app/cg-services-stage.scilifelab.se/scout.conf.py#L29
https://github.com/Clinical-Genomics/scout/tree/main/scout/models

# TODOs
- [ ] Get phenotype information
- [ ] Get panel information
- [ ] Fetch false positive variant data from SCOUT, see https://github.com/Clinical-Genomics/validations/pull/283#discussion_r2022327431
